name: documentation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Test Build
        run: |
          cd eigr_io
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: git
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "marcellanz@n-1.ch"
          git config --global user.name "marcellanz"
          cd eigr_io
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy